apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert
  template:
    metadata:
      labels:
        app: alert
    spec:
      containers:
        - name: alert-container
          image: acrlndqa.azurecr.io/laukendrasingh/alert:65
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env: # Setting environmental variables
            - name: CONFIG_NAME   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: config
---
apiVersion: v1
kind: Service
metadata:
  name: alert-loadbalancer
spec:
  selector:
    app: alert
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: alert-clusterip
spec:
  selector:
    app: alert
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
