apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert
  template:
    metadata:
      labels:
        app: alert
    spec:
      containers:
        - name: alert-container
          image: acrlndqa.azurecr.io/laukendrasingh/alert:66
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env: #Config-map
            - name: FIRST_NAME   #FIRST_NAME: key to read value from config-map
              valueFrom:
                configMapKeyRef:
                  name: alert-config-map
                  key: firstName
            - name: LAST_NAME   #LAST_NAME: key to read value from config-map
              valueFrom:
                configMapKeyRef:
                  name: alert-config-map
                  key: lastName
---
apiVersion: v1
kind: Service
metadata:
  name: alert-loadbalancer
spec:
  selector:
    app: alert
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: alert-clusterip
spec:
  selector:
    app: alert
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
