apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-deployment
  labels:
    app: alert
spec:
  replicas: 1
  selector:
    app: alert
  template:
    metadata:
      labels:
        app: alert
    spec:
      containers:
      - name: alert
        image: acrlndqa.azurecr.io/laukendrasingh/alert:26
        ports:
        - containerPort: 80
        - containerPort: 443
